const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),M=require('../model'),C=require('../comparison'),S=require('../schedule'),B=require('../backup');
(async()=>{
assert.equal(M.normalize({}).gueseoShopPrice,true);assert.equal(M.normalize({gueseoShopPrice:false}).gueseoShopPrice,false);
class E{constructor(tag,text=''){this.tag=tag;this.textContent=text;this.children=[];this.handlers={};this.value='';this.open=false;this.classList={add(){}};}append(...xs){for(const x of xs){if(x instanceof E){if(x.parentElement)x.parentElement.children=x.parentElement.children.filter(y=>y!==x);x.parentElement=this;}this.children.push(x)}}replaceChildren(...xs){this.children=[];this.append(...xs)}setAttribute(k,v){this[k]=v}addEventListener(k,f){this.handlers[k]=f}showModal(){this.open=true}close(){if(!this.open)return;this.open=false;this.handlers.close?.()}remove(){if(this.parentElement)this.parentElement.children=this.parentElement.children.filter(x=>x!==this)}querySelectorAll(tag){return this.children.filter(x=>x instanceof E).flatMap(x=>[...(x.tag===tag?[x]:[]),...x.querySelectorAll(tag)])}reportValidity(){return true}}
let worker,saves=[];const state=M.normalize({gueseoShopPrice:false,speedupIntent:'none',hasSamSword:true,canSainMission:true,cashRatio:2.3,gueseoMarketPrice:280000000});const current={meanFinish:999,log:[],purchases:[]};const ctx={Model:M,Completion:C,state,plan:current,JSON,Date,HOLIDAYS:{},compactEl:(tag,t)=>new E(tag,t),compactButton:(t,onclick,disabled=false)=>Object.assign(new E('button',t),{onclick,disabled}),document:{body:new E('body'),createElement:t=>new E(t),createTextNode:t=>t},Worker:class{constructor(){worker=this}terminate(){this.stopped=true}postMessage(p){this.payload=p}},calendarAPI:{saveSettings:async p=>{saves.push(p);return {ok:true,data:{}}}},renderCompactDashboard(){},dateTime:t=>'date '+t};vm.createContext(ctx);vm.runInContext(fs.readFileSync('efficiency-ui.js','utf8'),ctx);
ctx.openEfficiencySettings();const settings=ctx.document.body.children.at(-1),form=settings.querySelectorAll('form')[0],inputs=form.querySelectorAll('input'),shop=inputs[0];shop.checked=true;shop.onchange();assert(inputs[1].readOnly&&inputs[2].readOnly);inputs[1].onfocus();assert(!shop.checked);assert(!inputs[1].readOnly);shop.checked=true;shop.onchange();const hourInput=inputs.at(-1);hourInput.onfocus();assert(!hourInput.readOnly);form.onsubmit({preventDefault(){}});assert.equal(worker.payload.state.speedupIntent,'both');assert.equal(worker.payload.state.gueseoShopPrice,true);assert.equal(state.speedupIntent,'none');assert.equal(saves.length,0);
const p=(g,m,finish)=>({gueseoCount:g,masterCount:m,finish,log:[{phase:'sain',start:10,collect:finish,shortcutHours:m}],purchases:g?[{at:5,qty:g}]:[]});const results={base:p(0,0,300),economy:p(2,0,200),fast:p(2,3,100),current:p(0,0,300)};worker.onmessage({data:{result:results}});const comparison=ctx.document.body.children.at(-1);assert.equal(comparison.querySelectorAll('section').length,4);const sections=comparison.querySelectorAll('section');const comparisonsOf=section=>section.querySelectorAll('p').filter(x=>x.textContent.includes(' 대비: '));assert.equal(comparisonsOf(sections[0]).length,0);for(const section of sections.slice(1))assert.equal(comparisonsOf(section).length,3);assert(comparisonsOf(sections[3]).some(x=>x.textContent.startsWith('귀서만 사용 · 비용 절감 대비: 3,000원 추가')));assert(comparisonsOf(sections[2]).some(x=>x.textContent.startsWith('귀서 + 임달 사용 · 기간 단축 대비: 3,000원 절감')));const dateTexts=comparison.querySelectorAll('strong').map(x=>x.textContent);assert(dateTexts.includes('date 999'));assert.equal(comparison.querySelectorAll('button').filter(x=>x.textContent==='이 조건 적용').length,3);comparison.querySelectorAll('button').find(x=>x.textContent==='일정 보기').onclick();ctx.document.body.children.at(-1).close();comparison.close();assert.equal(saves.length,0);settings.close();
for(const [idx,intent,g,m]of [[0,'none',0,0],[1,'gueseo',2,0],[2,'both',2,3]]){const d=ctx.openEfficiencyPlanComparison({snapshot:state,source:M.planFingerprint(state),patch:{gueseoShopPrice:true},result:results,currentPlan:{...current,finish:999},now:1000,onApply(){}});await d.querySelectorAll('button').filter(x=>x.textContent==='이 조건 적용')[idx].onclick();const saved=saves.at(-1);assert.equal(saved.speedupIntent,intent);assert.equal(saved.gueseoTotal,g);assert.equal(saved.masterBudget,m);assert.equal(saved.gueseoShopPrice,true);assert.equal(saved.planSnapshot.finish,[300,200,100][idx]);assert.equal(saved.expectedSource,M.planFingerprint(state));M.validatePatch(saved);assert(M.normalize({...state,...saved}).planSnapshot);}
assert.equal(C.gueseoUnit({...state,gueseoShopPrice:true}),15000);assert(Math.abs(C.gueseoUnit(state)-12173.913)<.01);assert.equal(B.unpack(B.pack(M.normalize({...state,gueseoShopPrice:true}))).gueseoShopPrice,true);assert.notEqual(M.planFingerprint(state),M.planFingerprint({...state,gueseoShopPrice:true}));
const unready=M.normalize({...state,hasSamSword:false,canSainMission:false,sainReadyPlan:false});const beforeReady=saves.length;
const preview=ctx.openEfficiencyPlanComparison({snapshot:unready,source:M.planFingerprint(unready),patch:{gueseoShopPrice:true},result:results,currentPlan:{finish:null},now:1000,onApply(){}});
const ready=preview.querySelectorAll('input')[0],applyButtons=preview.querySelectorAll('button').filter(x=>x.textContent==='이 조건 적용');assert(applyButtons.every(x=>x.disabled));assert(preview.querySelectorAll('strong').some(x=>x.textContent==='date 300'));assert.equal(saves.length,beforeReady);
ready.checked=true;ready.onchange();assert(applyButtons.every(x=>!x.disabled));assert.equal(saves.length,beforeReady);ready.checked=false;ready.onchange();assert(applyButtons.every(x=>x.disabled));ready.checked=true;ready.onchange();await applyButtons[0].onclick();assert.equal(saves.length,beforeReady+1);assert.equal(saves.at(-1).sainReadyPlan,true);assert.equal(unready.sainReadyPlan,false);
const raw=M.normalize({...state,currentQty:280,currentTickets:0,speedupIntent:'both',gueseoShopPrice:true,efficiencyMode:'gueseo'}),r=C.compare(raw,{counts:[0]},new Date('2026-09-21T20:00:00'),{},S);assert.equal(r.base.masterCount,0);assert.equal(r.base.gueseoCount,0);assert.equal(r.economy.masterCount,0);assert(r.economy.gueseoCount>0);console.log('PASS: four cards, actual current schedule, independent both-use preview, shop pricing, no-save preview/cancel, each apply mode/counts/snapshot, backup and schedule engine');
})().catch(e=>{console.error(e);process.exit(1)});

